// build-fonts.mjs — self-host the Google Fonts (Inter Tight + IBM Plex Mono) so the site
// has no external font dependency (no render-blocking external CSS, no preconnect, GDPR-clean).
//
//   node tools/build-fonts.mjs
//
// Fetches the Google Fonts CSS (with a Chrome UA so woff2 is served), downloads the woff2
// files for the LATIN + LATIN-EXT + CYRILLIC subsets into assets/fonts/, then writes the
// @font-face rules into assets/core.css between /* fonts:start */ … /* fonts:end */ markers
// (idempotent — re-running replaces that block). core.css is linked first on every page,
// so the faces cost no extra request. Paths are relative to core.css (assets/), so they
// resolve from both root pages and /projects/ pages.

import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONTS_DIR = resolve(ROOT, 'assets', 'fonts');
const CORE = resolve(ROOT, 'assets', 'core.css');
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Inter+Tight:ital,wght@0,300..700;1,300..700&family=IBM+Plex+Mono:wght@400;500;600&display=swap';
const KEEP = new Set(['latin', 'latin-ext', 'cyrillic']);
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

mkdirSync(FONTS_DIR, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Split into (subset comment, @font-face block) pairs.
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)];
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const faces = [];
let downloaded = 0, bytes = 0;

for (const [, subset, body] of blocks) {
  if (!KEEP.has(subset)) continue;
  const get = (re) => (body.match(re) || [, ''])[1].trim();
  const family = get(/font-family:\s*'([^']+)'/);
  const style = get(/font-style:\s*([^;]+)/);
  const weight = get(/font-weight:\s*([^;]+)/);
  const range = get(/unicode-range:\s*([^;]+)/);
  const url = get(/src:\s*url\(([^)]+)\)/);
  if (!family || !url) continue;

  const name = `${slug(family)}-${style}-${weight.replace(/\s+/g, '_')}-${subset}.woff2`;
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  writeFileSync(resolve(FONTS_DIR, name), buf);
  downloaded++; bytes += buf.length;
  console.log(`  ${name}  ${buf.length} bytes`);

  faces.push(
    `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:swap;` +
    `src:url('fonts/${name}') format('woff2');unicode-range:${range}}`
  );
}

const block = `/* fonts:start — self-hosted, generated by tools/build-fonts.mjs; do not edit by hand */\n` +
  faces.join('\n') + `\n/* fonts:end */`;

let core = readFileSync(CORE, 'utf8');
if (/\/\* fonts:start[\s\S]*?\/\* fonts:end \*\//.test(core)) {
  core = core.replace(/\/\* fonts:start[\s\S]*?\/\* fonts:end \*\//, block);
} else {
  core = core.trimEnd() + '\n\n' + block + '\n';
}
writeFileSync(CORE, core);

console.log(`\n✔ ${downloaded} woff2 (${(bytes / 1024).toFixed(0)} KB) → assets/fonts/, ${faces.length} @font-face injected into core.css`);
console.log('Critical (preload candidates):', faces.length ? 'inter-tight-normal-cyrillic, inter-tight-italic-cyrillic' : '—');
